import jwt
from cryptography.fernet import Fernet # Fernet does Symmetric
from cryptography import x509
from cryptography.hazmat.backends import default_backend

# Load the Public Key generated by OpenSSL 
# The receiver uses this key to verify the signature.
try:
	with open("certificate.crt", "rb") as f:
		cert_pem = f.read()
		# We use the x509 library to extract public key from certificate
		certificate = x509.load_pem_x509_certificate(cert_pem, default_backend())
		public_key = certificate.public_key()
except FileNotFoundError:
	print("Error: certificate.crt not found.")
	exit()
print("--- RECEIVER: Processing Data ---")

# Load the Symmetric Key
try:
	with open("symmetric.key", "rb") as k:
		cipher_suite = Fernet(k.read())
except FileNotFoundError:
	print("Error: symmetric.key not found.")
	exit()

print("---RECEIVER: Symmetric Key loaded---")

# Read the token from the "network"
try:
	with open("token_transmission.txt", "r") as f:
		received_token = f.read()
except FileNotFoundError:
	print("Error: No token found in the network.")
	exit()

print(f"Token Received: {received_token[:20]}...") # :20 again

# Verify the Signature and Decode
try:
	decoded_data = jwt.decode(
		jwt=received_token,
		key=public_key,
		algorithms=["RS256"] # In brackets cause there might be multiple
	)

	print("\n[SUCCESS] INTEGRITY VERIFIED.")
	print("The signature is valid. Executing command:")
	
	encrypted_cmd = decoded_data['command']
	decrypted_cmd = cipher_suite.decrypt(encrypted_cmd.encode()).decode()
	print(f"Decrypted Command: {decrypted_cmd}")
	print(f"User Authorized: {decoded_data['user']}")

except jwt.InvalidSignatureError:
	print("\n[CRITICAL ERROR] SIGNATURE MISMATCH!")
	print("Security Alert: The data has been tampered with (Fake Data detected).")
	print("Action: Request Rejected.")

except Exception as e:
	print(f"\n[ERROR] Token invalid: {e}")
